// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _databaseURL = 'https://stress-detection-d208d-default-rtdb.europe-west1.firebasedatabase.app';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_K-Try9AIvvbZp25pQ0OTp20kCifM2U',
    appId: '1:1070444372105:web:8f5d250d7bb3237cac6658',
    messagingSenderId: '1070444372105',
    projectId: 'stress-detection-d208d',
    authDomain: 'stress-detection-d208d.firebaseapp.com',
    storageBucket: 'stress-detection-d208d.firebasestorage.app',
    measurementId: 'G-G7RMN0CDKS',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGzlQ0RvHE5hk3Ago7JU5B82Jomfan2M',
    appId: '1:1070444372105:android:f29763704f0414ccac6658',
    messagingSenderId: '1070444372105',
    projectId: 'stress-detection-d208d',
    storageBucket: 'stress-detection-d208d.firebasestorage.app',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWugMTH4_SLD7FKXGK0WOfzxDhdGzpek',
    appId: '1:1070444372105:ios:b2cd37cec6fb58deac6658',
    messagingSenderId: '1070444372105',
    projectId: 'stress-detection-d208d',
    storageBucket: 'stress-detection-d208d.firebasestorage.app',
    iosBundleId: 'com.example.stressDetection',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWugMTH4_SLD7FKXGK0WOfzxDhdGzpek',
    appId: '1:1070444372105:ios:b2cd37cec6fb58deac6658',
    messagingSenderId: '1070444372105',
    projectId: 'stress-detection-d208d',
    storageBucket: 'stress-detection-d208d.firebasestorage.app',
    iosBundleId: 'com.example.stressDetection',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_K-Try9AIvvbZp25pQ0OTp20kCifM2U',
    appId: '1:1070444372105:web:0bd8188abd2430e3ac6658',
    messagingSenderId: '1070444372105',
    projectId: 'stress-detection-d208d',
    authDomain: 'stress-detection-d208d.firebaseapp.com',
    storageBucket: 'stress-detection-d208d.firebasestorage.app',
    measurementId: 'G-RXCPFFR58E',
    databaseURL: _databaseURL,
  );
}
